// This file is normally generated by `wrangler types`. Minimal stub so
// TypeScript knows the shape of env while we bootstrap. Regenerate with:
//   npx wrangler types

interface Env {
	JWKS_CACHE: KVNamespace;
	GOOGLE_CREDENTIALS_JSON: string;
	GA_PROPERTY_ID: string;
	PUBLIC_FIREBASE_API_KEY: string;
	PUBLIC_FIREBASE_AUTH_DOMAIN: string;
	PUBLIC_FIREBASE_PROJECT_ID: string;
	PUBLIC_FIREBASE_STORAGE_BUCKET: string;
	PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
	PUBLIC_FIREBASE_APP_ID: string;
	PUBLIC_FIREBASE_MEASUREMENT_ID: string;
}
